# Generated by Django 4.1.7 on 2023-03-22 11:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'hobby',
            },
        ),
        migrations.CreateModel(
            name='HobbyCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('sport', 'sport'), ('coding', 'coding'), ('science', 'science'), ('art', 'art')], max_length=30)),
            ],
            options={
                'db_table': 'hobby_category',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='PersonLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hobbies_app.language')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hobbies_app.person')),
            ],
            options={
                'db_table': 'person_language',
                'unique_together': {('person', 'language')},
            },
        ),
        migrations.CreateModel(
            name='PersonHobby',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hobby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hobbies_app.hobby')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hobbies_app.person')),
            ],
            options={
                'db_table': 'person_hobby',
                'unique_together': {('person', 'hobby')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='hobbies',
            field=models.ManyToManyField(through='hobbies_app.PersonHobby', to='hobbies_app.hobby'),
        ),
        migrations.AddField(
            model_name='person',
            name='languages',
            field=models.ManyToManyField(through='hobbies_app.PersonLanguage', to='hobbies_app.language'),
        ),
        migrations.AddField(
            model_name='hobby',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies_app.hobbycategory'),
        ),
    ]
